[platformio]
default_envs = esp_tx

; Wspólne ustawienia dla obu płytek ESP32-C3-Zero
[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
    fastled/FastLED @ ^3.6.0
    adafruit/Adafruit NeoPixel @ ^1.11.0

; --- ŚRODOWISKO 1: NADAJNIK ---
[env:esp_tx]
build_src_filter = +<transmitter/*>
upload_port = COM6
monitor_port = COM6

; --- ŚRODOWISKO 2: ODBIORNIK ---
[env:esp_rx]
build_src_filter = +<receiver/*>
upload_port = COM7
monitor_port = COM7